---
#bibliography: bib/references0.json
---
<!-- The {.unnumbered} option here means that the introduction will be "Chapter 0." You can also use {-} for no numbers on chapters. -->

# Introduction {.unnumbered}
\chaptermark {Introduction}

In her new book, "Techno-Scientific Practices", Federica @russo2022 claims that knowledge has four essential properties: it is relational, embodied, distributed, and material. This means, in brief, that knowledge is not an intangible element of individual minds, but it is the physical inscription of information across a network of actors. This knowledge allows actors in that network to ascribe meaning to the world "out there". Russo builds on this notion to develop a theory of agency in the co-production of knowledge between scientists and technology, which asks us scientists to recognize that our ability to model the world depends on the knowledge embodied in the technology we use. Technology, then, plays an active role in producing further knowledge, and holds a degree of agency in the process. Russo deems this process of co-producing knowledge "poiêsis". Esoteric as the idea may seem, it draws on a powerful combination of Philosophy of Science, Philosophy of Technology, and Philosophy of Information to challenge the idea of knowledge as belonging to "psyche", and posits that knowledge is a physical thing that can be shared among individuals - and studied. I believe this perspective is not only broadly important for scientists and their work, but specifically relevant to the way we study knowledge in animals. We can know what an animal knows when our knowledge is shared. That is - when we ascribe the same meaning to world around us.

Not coincidentally, it is in large part the study of animals that brought us to this understanding of knowledge. Anthony @chemero2013 traces the tradition of embodied cognitive science, a foundation of Russo's work, to Darwin. Darwin's theory on the continuity of life challenged the predominant view in psychology that the existence of thought fundamentally held humans apart from other animals. Foundational Behaviorists that embraced Darwin's theory, such as B.F. Skinner, John Watson, and Ivan Pavlov, built theories of learning by studying the reinforcement of behavior in animals. Yet, in rejecting the "introspective" methods of other psychologists, these animal researchers left a gap between the development of behavior through reinforcement and the complex psychology of humans. Descartes' rationalist view of humans still reigned, and even as the prominent philosopher Martin Heidegger wrote extensively about the nature of "being in the world" as a continuous process of affording meaning to the state of matter around us [@heidegger1962being], he also described animals as "poor-in-world", unable to conceive of things around them as "being" [@heidegger1993letter].

There was at least one psychologist, however, that found found a middle ground. Edward Tolman's "Purposive Behavior in Animals and Men" [@tolman1951purposive] describes an extensive series of experiments, mostly based on the navigation of rats through mazes, in which animals 1) latently acquired information about the world around them, 2) behaved in novel situations as though they were considering multiple courses of action, and then 3) pursued courses of action that they could only have inferred (correctly) would most effectively bring about desired outcomes, no reinforcement required. Most famously, he demonstrated that when he changed the structure of a maze, rats would spontaneously take shortcuts to out-of-sight food rewards. Through these experiments, Tolman detailed an elaborate framework of the mind, which intricately connected the behaviorists' notion of reinforcement learning to Heideggers notion of "being in the world". In his central claim, he made analogy of the mind to a map, which modeled the world outside by connecting concepts by "distance" and "direction". The key target of reinforcement, in this framework, was not stimulus-action pairs that yielded (un)desirable outcomes, but distance and direction models that accurately predicted the future. As concepts in an individual's cognitive map were arranged and built up hierarchically into knowledge of the world, he claimed, increasingly complex thoughts, "raw feels", and even consciousness would emerge naturally.

Tolman's took a long time to become popular. It was not until @okeefe1976 measured the activity of individual "place neurons" in the brains of rats and claimed that these provided embodied and material evidence of Tolman's cognitive map that "cognitivism" entered the psychological mainstream. The decades of neuroscience research since have slowly built a rich and compelling picture of how distance and direction can be embodied by linking place neurons to grid neurons, and how cognitive maps can emerge as these neurons are integrated into memory traces (engrams) through reinforcement [@josselyn2020; @leutgeb2005; @weber2018]. Validating the ideas of both Tolman and Heidegger, the most fundamental feature of this system is increasingly seen not as a the mapping of space, but of time [@dragoi2011; @ekstrom2018]. In today's psychology, the cognitive map concept is tightly connected to the study of episodic memory, and the notion that behavioral flexibility emerges from the ability to map information from the past onto possible futures [@suddendorf2007].

Even now, a tug-of-war exists between the rationalist approach, which identifies elements of human thought that demonstrate our unique capacity for reflection, and the embodied approach, which claims that all thought has material origins traceable through an organisms history. For example, a distinction is often made between "episodic-like" memory, evidenced by animals' ability to act according to information about when, where, and how they experienced something, and episodic memory, which includes the awareness of one's-self "being" in the memory [@clayton2017; @crystal2019]. Tulving describes the representation of self in memory as *auto-noesis*, and claims that even if animals do this too, it is not possible to get in their heads in a way by which we could know for sure [@tulving2005]. Perhaps he is right, or perhaps it possible to understand how the process by which *auto-noesis* emerges and identify the signatures of that process in animal behavior, as Tolman once did when he sought evidence that rats make inferences and visualize the future.

If we are to hold the view that knowledge is relational, embodied, distributed, and material (as follows from Tolman's theory of cognitive maps) and that it is co-produced by networks of human *and* non-human actors (as put forth by Russo), then it is possible to see knowledge of the self not as an innate, ineffable aspect of human psychology, but as tangible, and perhaps inevitable, product of a cognitive organism engaging with the world around it. To study this process, however, we must step outside the world of laboratories and rats, and into the complex, poorly defined world in which the human capacity for *auto-noesis* evolved. We must ask how cognitive maps are built, from the ground-up, and put ourselves back into the equation. What is the distance and direction between the way we move through the world and the way an animal moves through world, and what can then be inferred about the knowledge we share?

The rest of this thesis is not about self-awareness or consciousness. I try to limit myself to the marginally less messy concepts of knowledge, learning, and inference. But my background as a cognitive psychologist with an interest in primate theory of mind informs the whole endeavor. My mission, in starting this Ph.D. program, was to take the big questions of psychology and primate evolution to the field, and ask how cognition works when you take away the controls. What I discovered is that in the field of behavioral ecology, the concept of cognitive maps is used more like a tool than a theory (though it still often traced back to Tolman and the use of shortcuts by rats in mazes). The cognitive map, in ecology, takes the most literal form of Tolman's cognitive map: a mental topological representation of space. Though this may not accurately describe most animals' knowledge, it can be useful for approximating animal knowledge when studying their decision making. And, if the use of shortcuts is demonstrated in wild animals, its proof of a cognitive map's existence can be rightfully hailed as a milestone for the study of animal cognition. In each chapter of this thesis, I make an attempt to integrate the ecological concept of cognitive maps (which I henceforth call topological maps) and the pyschological concept of cognitive maps. 

What I mean by this is, I make an effort in each chapter to measure the ways different animal's movement reflects an inference at a specific spatial scale, and what the nature of this inference says about the animals' knowledge. In the first chapter, I explore multi-destination route-optimization by primates in local resources arrays. I ask how their movement provides evidence that they have learned either the specific patterns that optimize a given array, or general strategies that yield efficient routes in many arrays. In the second chapter, I bring this controlled, lab test to the messy field, exploring how kinkajous forage for flowers in the analagous but much more complicated crown of a balsa tree. Then I expand the scale, asking how kinkajous learn routes and navigate between feeding stations I experimentally baited with food over nearly two months. Finally, I expand the scope, analyzing the movements of four different species for signs of spatial inference as they forage for a particularly essential and dynamic food resource over a two three-month seasons. In the process, I have repeatedly broken down and rebuilt my own understanding of the nature of cognition. I hope, by the end, the reader might share in some facet of that knowledge.
