setwd("C:/Users/avining/ownCloud/Alexanders_Dissertation/6. Crown Complexity/DATA/Balsa Obs Data/AO data 12_1_20")
behaviors <- read.csv("behaviorsTable.csv")
comments <- read.csv("commentsTable.csv")
continuousVariables <-  read.csv("continuousVarsTable.csv")
dayVariables <- read.csv("dayVarsTable.csv")
focals <- read.csv("focalsTable.csv")
focalVariables <- read.csv("focalVarsTable.csv")
scans <- read.csv("scansTable.csv")
scanVariables <- read.csv("scanVarsTable.csv")
sessions <- read.csv("sessionsTable.csv")
